all:
  hosts:
    tollgate-vps:
      ansible_host: "{{ lookup('env', 'VPS_IP') }}"
      ansible_user: debian
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      ansible_become_password: "{{ lookup('env', 'VPS_PASSWORD') | default('', true) }}"
    tollgate-vps-old:
      ansible_host: "{{ lookup('env', 'OLD_VPS_IP') }}"
      ansible_user: debian
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      ansible_become_password: "{{ lookup('env', 'OLD_VPS_PASSWORD') | default('', true) }}"
    tollgate-backup:
      ansible_host: "{{ lookup('env', 'BACKUP_MACHINE_HOST') }}"
      ansible_user: c03rad0r
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  children:
    m1:
      hosts:
        tollgate-vps:
    m2:
      hosts:
        tollgate-vps-old:
    backup:
      hosts:
        tollgate-backup:
